### PR TITLE
Support Tizen platform

### PR DESCRIPTION
**Pull request by myroot**
* Support tizen40 TargetFramework  (https://developer.tizen.org/development/api-reference/.net-application)
* Unsupported features 
 All Transformations
 GIF animated image

### CODE REVIEW

**Comment by myroot** [comment]
Hi, I'm tizen developer,
I'd like to contribute to this project to support tizen platform

I made some of patches, it enable to FFImageloading in Xamarin.forms for tizen
So, I submit this PR.

**Comment by daniel-luberda** [comment]
Hi @myroot,

That is so cool! Thank you for your collaboration. I reviewed all the changes and will merge it now. Good job! Thanks! :)

**Comment by daniel-luberda** [comment]
BTW: @myroot Do you know if Tizen supports Visual Studio for Mac? Currently the project file is not recognised.

**Comment by rookiejava** [comment]
Howdy, @daniel-luberda.  Unfortunately, tizen TFM is not available in VS for Mac yet. However, you can use https://github.com/mrward/temp-addin-upload/tree/master/DotNetCoreSupportAnyTargetFramework. With this addin,  tizen TFM is well recognized on VS For Mac. I think it is a temporary way to use tizen project until VS for Mac officially support tizen TFM.

**Comment by daniel-luberda** [comment]
@rookiejava Thanks for info! It'll be definitely useful for me for things like fixes, code refactorings, etc. I just tested it.

**Pull request merged**
