### PR TITLE
Adds Mac support

### PR DESCRIPTION
**Pull request by Sevenish**
Adds Mac support based on IOS code.
No support for webp.
No support for animated gifs,.
No support for image fadein.

If using sandboxing on the Mac app a sandbox valid DiskCachePath must be provided through ImageService.Instance.Initialize()

### CODE REVIEW

**Comment by daniel-luberda** [comment]
Great addition! Thank you for your collaboration. I'll try to merge it soon. For a better maintenance we should share as much code as possible with iOS. We could use `conditional symbols` for that (eg. for replacing `UIImage` with `NSImage`, etc.

**Comment by Sevenish** [comment]
Yes that would be good. 
I could add another new shared project for the shared code between IOS and Mac.

Also in some classes use using with condital like:
#if __IOS__
using AppleImage = UIKit.UIImage;
#elsif __MACOS__
using AppleImage = AppKit.NSImage;
#endif

Does that sound good to you? If yes a will rewrite a better pullrequest.

**Comment by daniel-luberda** [comment]
That would be great. 

It could be another shared project,  or you could add files as a links only from iOS project. 

On iOS there's an existing conditional symbol: '__IOS__',  the rest sounds great :)

**Comment by Sevenish** [comment]
Refactored Mac support with a shared project for IOS and Mac

**Comment by molinch** [comment]
That is really an awesome PR

**Comment by daniel-luberda** [comment]
Merged. We have now a basic support, but it'll be also nice to add: 

- Xamarin.Forms support
- SVG support
- Transformations support
- WebP, GIF support
- FadeIn support

Thanks @Sevenish

**Comment by daniel-luberda** [comment]
2.2.12.497 nuget with Mac support released.

**Comment by Sevenish** [comment]
Great, fast turnaround. Already using it in a Mac app

**Pull request merged**
