### PR TITLE
Extremely BASIC iOS Gif support. (Have to start somewhere)

### PR DESCRIPTION
**Pull request by alanspires**
This includes VERY basic GIF support for iOS with an included sample. I would imagine that as users needs for more advanced GIF support come up, we will see additional PR's.

### CODE REVIEW

**Comment by molinch** [comment]
Hi @alanspires, could we discuss by email? You can find my email here: https://github.com/molinch

**Comment by alanspires** [comment]
Further research. iOS saves GIF's as 1 frame JPEG's. Big comapibes like FB or twitter seem to have access to metadata that gives them an actual link to the GIF. But regardless.. Scenario...

1. Go to giphy.com save it library. Saves as a JPEG. If you copy and paste into iMessage it magically reanimates. If you get the filePath in code it leads to a JPEG with no meta. So....

This destroys caching....
Without saving the original URL it's impossible to use helper routines to re-animate. 

REDDIT makes you store GIF's as a link to the original (makes sense considering). This works as you have the data of the image.

How would one reload a GIF stored as a JPEG?

Tricky.

**Comment by daniel-luberda** [comment]
@alanspires Thank you for great PR. I merged it, we can optimise it later and (hopefully) add Android support too.

**Comment by alanspires** [comment]
Sounds good!

**Pull request merged**
