### PR TITLE
Fix i os resource loading

### PR DESCRIPTION
**Pull request by escamoteur**
Hi Daniel,

when  omitting the file extensions for bundled resources on iOS they did no longer load.

Problem as like described here

http://stackoverflow.com/questions/21062628/nsbundle-pathforresource-returns-nil

Additionally `file`  wasn't reset inside the foreach

Cheers
Thomas

### CODE REVIEW

**Comment by alanspires** [comment]
Beat me too it, was just about to push my own. Found the same in my fix. 👍

**Comment by molinch** [comment]
@daniel-luberda Code looks good, however I cannot really test this since I no longer have Xamarin dev. stuff.

**Comment by escamoteur** [comment]
@molinch do you have any idea where Daniel could be? I haven't heard from it for over a week

**Comment by daniel-luberda** [comment]
Thanks for PR! Merging it now! :) 👍

**Pull request merged**
