### PR TITLE
Build on AppVeyor!

### PR DESCRIPTION
**Pull request by mattleibow**
Here is the results!

https://ci.appveyor.com/project/mattleibow/ffimageloading/build/13/artifacts

### CODE REVIEW

**Comment by mattleibow** [comment]
This should fix those build errors :) And I left some of the warnings in (just removed the no XML ones). The others should be fixed, so if you get annoyed, it is a good thing 😄 

I'll probably fix that in a new PR just so that I can say I have a few PRs of this awesome library 😆

**Comment by mattleibow** [comment]
I  might even say that we should remove the `Windows Release` configuration as this is not necessary any more.

**Comment by molinch** [comment]
Wow that's pure awesomeness! it's really crazy what you achieved. Many many thanks @mattleibow !!!
It will help a lot ! 👍 👍 👍

**Comment by molinch** [comment]
@mattleibow So for a lib it's not mandatory to have a Xamarin license configured in AppVeyor, right?

**Comment by daniel-luberda** [comment]
@mattleibow Great! Many thanks for PR!! :)

**Comment by mattleibow** [comment]
@molinch Nope, just to build an app. But, now with the acquisition by MS, Xamarin is free - like in free beer! 100% free and open source: open.xamarin.com

@daniel-luberda No prob, it was great fun!

**Pull request merged**
