### PR TITLE
Added android XML images support

### PR DESCRIPTION
**Pull request by AndreiMisiukevich**
So, now you can use PDF images for iOS and XML for android
I apologize for my code in advance =)
I think it can be useful for somebody.

### CODE REVIEW

**Comment by daniel-luberda** [comment]
That's cool! Thanks!  I'll try to review it when I'll have some free time. 

From a quick review I am wondering if we could remove need for `WidthRequest` and `HeightRequest`. Maybe something similar as in `SvgDataResolver`?

**Comment by AndreiMisiukevich** [comment]
hmm, I thought about it.. but it seemed as over design in XML files case.
because we've got separate Image View for Svg - MvxSvgCachedImageView / SvgCachedImage
Maybe, it will be strange to create new type for this (e.g. XmlCachedImage)

And as for SVG, We check extension of file (name.svg), but for xml we can't.
Or just I don't see the whole situation =)

**Comment by AndreiMisiukevich** [comment]
So, I just want to say, that we have to execute platform code (reading file, retrieving file extension), before choosing any data resolver.. but it seems rather difficult for me)

Thanks

**Comment by AndreiMisiukevich** [comment]
hm, or we are able to document some requirements for naming.
e.g. **name__xml** will mean, that we should retrieve **name** resource for all platforms, but for android it will take name.xml 
=)
Maybe, it's too radical idea)

**Comment by AndreiMisiukevich** [comment]
@daniel-luberda 
Sorry for disturb.
Have you looked through this PR yet?

**Comment by daniel-luberda** [comment]
@AndreiMisiukevich Sorry, not yet - I'll need to refactor some things here, so I'll need some more time for that (after fixing other issues)

**Comment by daniel-luberda** [comment]
I would prefer the same approach as SVG files. `IVectorDataResolver` should be used: 

```C#
    public interface IVectorDataResolver : IDataResolver
    {
        int VectorWidth { get; }

        int VectorHeight { get; }

        bool UseDipUnits { get; }

        Dictionary<string, string> ReplaceStringMap { get; set; }
    }
```

As you see, it already contains `VectorWidth` / `VectorHeight` properties. We don't need to modify `TaskParameter`, `ImageInformation` and generating custom key, as it does it automatically for us when this interface is used. 

We could create `AndroidXmlDataResolver` and `iOSPdfDataResolver`, similarly to `SvgDataResolver.cs` https://github.com/luberda-molinet/FFImageLoading/blob/master/source/FFImageLoading.Svg.Shared/SvgDataResolver.cs

Then you would load images as: 

`var task = ImageService.LoadCompiledResource("someFile.xml").WithCustomDataResolver(new AndroidXmlDataResolver(width: 200, height: 200))`, etc

The problem is that `IVectorDataResource.Resolve` must return a `Stream` but we can return just a null and add another property to it like `string ResourceId { get; }`, I could refactor the code to support that scenario (pass that id to decoders).

**Comment by daniel-luberda** [comment]
Or even we could create platform specific extensions like: 

`var task = ImageService.LoadXmlResource("someFile.xml", width: 200, height: 200))`
`var task = ImageService.LoadPDFResource("someFile.pdf", width: 200, height: 200))`, etc

**Comment by daniel-luberda** [comment]
>>> hmm, I thought about it.. but it seemed as over design in XML files case.
because we've got separate Image View for Svg - MvxSvgCachedImageView / SvgCachedImage
Maybe, it will be strange to create new type for this (e.g. XmlCachedImage)

The only reason why there're a separate SVG controls is that SVG support is provided in a different nuget package. If we'll have xml/pdf support in base packages, we can handle loading of those files without any problem.

**Pull request closed without merging**
