### PR TITLE
Creating extension for Color object

### PR DESCRIPTION
**Pull request by ckrempp91**
Creating the extension for Xamarin.Forms.Color object to allow easy creation of float array for color transformations, this also has the optional parameter of brightness to be adjustable.

### CODE REVIEW

**Comment by ckrempp91** [comment]
Currently I have tested this on Android and UWP, the colors match. Here is an example of how to use the code:

`Color.Red.ColorToMatrix(0.1f)`
or
`Color.Red.ColorToMatrix()`

If you do not specify a brightness value, then it will assume a default value to match the exact definition set in the Xamarin.Forms.Color object.

**Comment by molinch** [comment]
Great that definitely helps. Many thanks @ckrempp91 👍 
Would you mind updating the Wiki with your examples?

**Comment by ckrempp91** [comment]
@molinch sure, I will update try to update the wiki when I get home.

**Comment by ckrempp91** [comment]
@molinch I have updated the documentation in the Transformation guide to include the ColorToMatrix extension method. If you have any suggestions, please feel free to make adjustments.

**Comment by daniel-luberda** [comment]
@ckrempp91 Thanks for a PR :)

**Comment by ckrempp91** [comment]
@daniel-luberda @molinch I think there is a problem with Xamarin.FFImageLoading.Forms package because I attempted to use the 2.1.6-pre-109 and it does not show the ColorExtensions class in the object broswer.

**Comment by daniel-luberda** [comment]
It's fixed with https://github.com/luberda-molinet/FFImageLoading/commit/b85fd3f54a0918e4e35c5b159f4f8b01068cdccc

**Comment by ckrempp91** [comment]
Alright, thank you!

**Pull request merged**
