### PR TITLE
Fixed for Nuget package generation

### PR DESCRIPTION
**Pull request by ravensorb**
Updated paths to be nuspec spec compliant
Combined Windows nuspec with main nusepc
Refactored dependencies to be a little cleaner

### CODE REVIEW

**Comment by molinch** [comment]
Awesome! Dependencies are cleaner now.

Two remarks:
- Why have you added this dependency? https://github.com/ravensorb/FFImageLoading/blob/79ee3b257d9ebbf91e4e1a633804678e6440e530/source/Xamarin.FFImageLoading.nuspec#L44
- I am pretty sure that URLs should have a slash, not a backslash: https://github.com/ravensorb/FFImageLoading/blob/79ee3b257d9ebbf91e4e1a633804678e6440e530/source/Xamarin.FFImageLoading.Forms.nuspec#L10

**Comment by ravensorb** [comment]
For the first one -- I didn't, it was in the FFImageLoading.Windows.nuspec file. I just copied it over.
For the 2nd one, good catch. I just fixed that

**Comment by molinch** [comment]
Ah yes that's because Windows package has been merged.
Many thanks for your help. We should be able to deliver a new RC very soon.

**Comment by molinch** [comment]
@ravensorb In the end we had to revert the changes: it was no longer packing on Mac.
Anyway I don't think that was the cause of your issue: I checked a few nuspec accross internet and many have forward slashes too. So both kind of slashes are working IMO.

Maybe you have some corruption in your Nuget cache?
http://stackoverflow.com/questions/19601350/strange-nuget-error-while-enabling-nuget-package-restore

Can you try to remove FFImageLoading packages from your cache: %localappdata%\NuGet\Cache and download them again?

**Comment by ravensorb** [comment]
Note sure - if you look at the actual [spec](https://docs.nuget.org/create/nuspec-reference) it requires \ so I have always used them.  

If it helps, I have now tried installing the current rc2 on 4 different computers (2 are brand new builds) and all fail with the same error (also 2 team members hit the same issue).  The only solution want to use the rc3 that I created -- that works 100% of the time (even when installing the package on the OSX machine.

Maybe switch to have appveyor create the package for you?

**Comment by molinch** [comment]
@ravensorb Many thanks for the time invested on this. It help a lot!

It is true that the spec has examples with backslashes therefore they have zero page that says "you have to use backslashes".

Still what I don't get is why now, all of sudden, it just stops working on PC. We always had these slashes and nobody ever complained. Something is unclear to me...
Could it be related to VS 2015? or something new? On Mac/XS it works as a charm.

@daniel-luberda Anyway we should find a solution ASAP so I should probably revert the last 2 commits...

**Comment by ravensorb** [comment]
it could be -- everyone I am working with is using VS2015 with Update 2.

**Comment by molinch** [comment]
@ravensorb Unfortunately I only work on Mac so making the nuget is quite challenging for me (since Windows Phone assemblies are required too). That's why we initially had separate nugets for WP: so I could still upload nugets for the core stuff.

Usually @daniel-luberda does it and uploads the nugets. Right now Daniel is quite busy and won't be available to do this.

Would you be interested to join the project? This way we could rely on 2 persons to pack the nuget... And if you are interested to do more than that then we are more than happy.

**Comment by ravensorb** [comment]
Any thoughts to leveraging a free AppVeyor account to automate the building of the solutions and of the nuspec packages (I am using it for 3 or 4 different projects now and it works well).

**Comment by molinch** [comment]
AppVeyor would be the greatest solution however you need a Xamarin license.
Unfortunately using my company's licence, on a 3rd party website, for an OSS project, won't be allowed. I requested an OSS license to Xamarin, I will see how it goes.

**Comment by molinch** [comment]
@ravensorb Daniel managed to build it on Windows and uploaded new nugets.
Could you give these a try?

**Comment by ravensorb** [comment]
Good news is -- it installs :)  For the most part -- if I install the Xamarin.FFImageLoading.Forms, the Xamarin.FFImageLoading project doesn't auto install into a UWP project. However I can add it manually.  Probably just a dependency targetFramework missing.

Image

Bad news -- I am still getting generation image errors without details (related to another issue I filed) :grin:

**Comment by molinch** [comment]
@daniel-luberda Could you check the UWP issue?
On my side I will see what happens with the generation issue when an authentication token is needed.

**Pull request merged**
