### PR TITLE
Image Removal Logic Change

### PR DESCRIPTION
**Pull request by GZidar**
Changed to force image that has been invalidated from cache to also be removed from the displayed cache and reuse pool.

### CODE REVIEW

**Comment by GZidar** [comment]
Please note that all 56 tests passed when run within Visual Studio. I am not sure how to kick the check off again to see if the failure is repeatable.

**Comment by daniel-luberda** [comment]
Hi @GZidar,

Could you write more about your PR? Eg. why do you want to remove image from reuse_pool?

**Comment by GZidar** [comment]
When an image is loaded from a web server, the cache key contains the URI of that image source. Thus when that image is updated on the server side invalidating the cache (ie evicting the image) does not work because the URI of the image source has not changed (only the image data). So, the requirement here is to fully purge the image data from all cache sources when the eviction is called.

The verbose logs show that when an image cache entry is invalidated and the system attempts to reload the image it always finds that image in the reuse pool and therefore displays the old (now incorrect) image.  By removing the image from the display cache and the reuse pool we can be sure that when the image is requested again it forces it to read the new image from the webserver rather than just serving up what has been cached locally.

**Comment by daniel-luberda** [comment]
Merged. Thank you.

**Pull request merged**
