### PR TITLE
Remove unnecessary asset catalog code

### LINKED ISSUE #534: Simple.iOS.Sample Loading Placeholder is broken
I downloaded the code cause I was seeing this is my own project. But the same issue is here. Run the sample and view the output.

System.IO.FileNotFoundException: placeholder
  at FFImageLoading.DataResolvers.BundleDataResolver+<Resolve>d__1.MoveNext () [0x006a9] in E:\Eds Projects\FFImageLoading-master\source\FFImageLoading.Touch\DataResolvers\BundleDataResolver.cs:140 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Library/Frameworks/Xamarin.iOS.framework/Versions/10.4.0.123/src/mono/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:143 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00047] in /Library/Frameworks/Xamarin.iOS.framework/Versions/10.4.0.123/src/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:187 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (Syst
em.Threading.Tasks.Task task) [0x0002e] in /Library/Frameworks/Xamarin.iOS.framework/Versions/10.4.0.123/src/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:156 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x0000b] in /Library/Frameworks/Xamarin.iOS.framework/Versions/10.4.0.123/src/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:128 
  at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/10.4.0.123/src/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:535 
  at FFImageLoading.Work.ImageLoaderTask`2+<ShowPlaceholder>d__108[TImageContainer,TImageView].MoveNext () [0x001b1] in E:\Eds Projects\FFImageLoading-master\source\FFImageLoading.Common\Work\ImageLoaderTask.cs:380

### PR DESCRIPTION
**Pull request by nmilcoff**
Asset catalogs are handled automatically behind the scenes by `UIImage.FromBundle(filename)`.

This PR fixes #534, it can be tested on the iOS sample project.

### CODE REVIEW

**Comment by daniel-luberda** [comment]
Hi @nmilcoff, 

https://developer.xamarin.com/api/type/UIKit.NSDataAsset/ should have a better performance. Could you give a case when it's not working, whether `UIImage.FromBundle` is? :)

**Comment by nmilcoff** [comment]
Hi @daniel-luberda yes, the sample project in the repository. If you try it with the current version it doesn't work. But it does with the changes of this PR

**Comment by daniel-luberda** [comment]
@nmilcoff Thank you for the info. I fixed it with a different approach, primarily `NSDataAsset` is used (because of a better performance), then `UIImage.FromBundle` is used. I hope it'll fix it for you. Thanks!

**Comment by nmilcoff** [comment]
Awesome @daniel-luberda! Thank you for fixing this

**Pull request closed without merging**
